theme: minima
plugins:
  - jekyll-feed
title: Shwetha Kunnam
email: skunnam at caltech dot edu
github_username: sidewalkill
linkedin_username: [side](https://www.linkedin.com/in/shwetha-kunnam-bb4363195/)

description : >- 
  :)
header_pages:
 - index.md
