theme: minima

title: Shwetha Kunnam
email: skunnam@caltech.edu
github: https://github.com/sidewalkill
linkedin: https://www.linkedin.com/in/shwetha-kunnam-bb4363195/

description : >- 
  :)
header_pages:
 - index.md
