theme: minima
plugins:
  - jekyll-feed
title: Shwetha Kunnam
email: skunnam at caltech dot edu
github: sidewalkill
linkedin: https://www.linkedin.com/in/shwetha-kunnam-bb4363195/

description : >- 
  :)
header_pages:
 - index.md
